Fix failing zip_0233 test
Test was failing due to a type mismatch:

```
error[E0308]: mismatched types
   --> zcash_primitives/src/transaction/tests.rs:410:29
    |
410 |             .map(|s| Script(s.clone()))
    |                      ------ ^^^^^^^^^ expected `Code`, found `Vec<u8>`
    |                      |
    |                      arguments to this struct are incorrect
    |
    = note: expected struct `Code`
               found struct `Vec<u8>`
```